#!/bin/bash
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root." >&2
    exit 1
fi

# Format
b='\033[1m'
r='\033[0m'

# Colors
RED='\033[0;31m'
YELLOW='\033[1;33m'

# Misc
notify="${RED}[!]:"
info="${YELLOW}[i]:"

display_menu() {
# Intro
echo '             ____  ____        ___    ___            '
echo '|""|_        |  \  |  |    __  |  \  /  |            '
echo '|__|\\_      |   \ |  |    | | |   \/   |            '
echo ' ||  "\\|""| |    \|  |____| |_|        | __ ___ ___ '
echo ' ||  _//|__| |  .\ `  |  _ \ __|  |\/|  |/ _` | \|_ |'
echo '|""|//"      |  | \   |  __/ |_|  |  |  | (_| | | | |'
echo '|__|"        |__|  \__|____|\__|__|  |__|\__,_|_| |_|'
echo

# The menu
    echo -e "${b}Network Manager Tool${r} | by KFM"
    echo
    echo -e "$info Available networks $r"
nmcli dev wifi
    echo "
    
        +--------+----------------------------+
        | Option | Action                     |
        +--------+----------------------------+
MANAGE  | ainf   | Show All Network Adapters  |
        | dinf   | Show Adapters information  |
        | winf   | Show Wireless Adapters     |
        | unet   | Up the Network Card        |
        | dnet   | Down the Network Card      |
        | rest   | Restart Network Manager    |
        | rmac   | Random Mac Address         |
        | cmac   | Custom Mac Address         |
        | cipa   | Custom IP Address          |
        +--------+----------------------------+
SCAN    | fscn   | Full scan                  |
        | cscn   | Channels scan              |
        | sscn   | ESSID scan                 |
        +--------+----------------------------+
CONNECT | gsts   | General Status             |
        | ldev   | List Network Devices       |
        | lcon   | List Connection            |
        | wcon   | Connect to Wifi AP         |
        | 
        |
        | i      | About NetMan Tool          |
        | q      | Quit                       |
        +--------+----------------------------+

"
}

while true; do
    display_menu
    read -p $'\033[1;34mNetMan@'"$HOSTNAME"$': $ \033[0m' option
    case $option in
	q)
        clear
		echo
		echo "Goodbye"
		exit
	;;
    ainf)
        ifconfig
    ;;
    dinf)
        clear
        nmcli dev show
    ;;
    winf)
        iwconfig
    ;;
	unet)
		ifconfig wlan0 up
		echo wlan0 is up
	;;
    dnet)
        ifconfig wlan0 down
    ;;
    rest)
        systemctl restart NetworkManager
        echo "[i]: Network Manager restarted"
    ;;

    1)
        while true; do
	clear
            echo "Full scanning"
            iwlist wlan0 scan
            echo "Press Enter to return to the main menu or ^C to exit."
            read
	clear
            break
        done
        ;;
    2)
        while true; do
            clear
	echo "ESSID scanning"
            iwlist wlan0 scan | grep -i essid
            echo "Press Enter to return to the main menu or ^C to exit."
            read
	clear
            break
        done
        ;;
    3)
        while true; do
	clear
            echo "Channels scanning"
            iwlist wlan0 channel
	echo
            echo "Press Enter to return to the main menu or ^C to exit."
            read
	clear
            break
        done
        ;;
    4)
        while true; do
            clear
	echo "General status"
            nmcli general status
            echo
	echo "Press Enter to return to the main menu or ^C to exit."
            read
	clear
            break
        done
        ;;
    5)
        while true; do
            clear
	echo "Available devices"
            nmcli dev
            echo "Press Enter to return to the main menu or ^C to exit."
            read
	clear
            break
        done
        ;;
    6)
        while true; do
            clear
	echo "Connection:"
            nmcli connection show
            echo "Press Enter to return to the main menu or ^C to exit."
            read
	clear
            break
        done
        ;;
    7)
        while true; do
	echo "Enter network name or SSID:"
            read netname
            echo "Enter password:"
            read -s netpass
            nmcli dev wifi connect "$netname" password "$netpass"
            echo "Press Enter to go back or refresh or ^C to exit."
            read
	clear
            break
        done
        ;;
    "")
	clear
        echo -e "$notify No selection $r"
        ;;
    *)
    clear
	echo -e "$notify Select a correct option $r"
        ;;
    esac
done
